{% set name = "molecule-generation" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molecule_generation-{{ version }}.tar.gz
  sha256: c5b6e477c760fe88a5be13f1fc0c71310d31be27695202bef047286a3695773f

build:
  entry_points:
    - molecule_generation = molecule_generation.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - dpu-utils >=0.2.13
    - more-itertools
    - numpy >=1.19.2
    - protobuf >=3.20,<4
    - rdkit
    - scikit-learn >=0.24.1
    - tensorflow >=2.1.0,<3
    - tf2-gnn >=2.13.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - molecule_generation
  commands:
    - molecule_generation --help

about:
  home: https://github.com/microsoft/molecule-generation/
  summary: Implementations of deep generative models of molecules.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
